import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screeen flex`}
      >
        {/* サイドバー */}
        <aside className="w-48 bg-gray-100 p-4 space-y-2">
          <Link href="/dashboard">Dashboard</Link>
          <br />
          <Link href="/bookmarks">Bookmarks</Link>
          <br />
          <Link href="/following">フォロー中</Link>
        </aside>

        {/* メイン */}
        <main className="flex-1">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
